version: "3.8"

services:
  pufferpanel:
    image: pufferpanel/pufferpanel:latest
    container_name: pufferpanel
    ports:
      - "8523:8080"
      - "5657:5657"
    volumes:
      - ${APP_DATA_DIR}/config:/etc/pufferpanel
      - ${APP_DATA_DIR}/data:/var/lib/pufferpanel:z
    restart: on-failure
