version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: pufferpanel_pufferpanel_1
      APP_PORT: 8080 

  pufferpanel:
    image: pufferpanel/pufferpanel:latest
    container_name: pufferpanel
    ports:
      - "5657:5657"
    volumes:
      - ${APP_DATA_DIR}/config:/etc/pufferpanel
      - ${APP_DATA_DIR}/data:/var/lib/pufferpanel:z
    restart: on-failure